version: '3.7'
services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: posgtres
  web:
    build: .
    command: bash -c "sleep 7 &&
             python /usr/src/project_restapi/manage.py makemigrations &&
             python /usr/src/project_restapi/manage.py migrate &&
             python /usr/src/project_restapi/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/project_restapi
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres_data: